name: KrellixMainframe
on:
  issues:
    types: [opened]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: System Processing
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: python play.py
      - name: Deploy Changes
        run: |
          git config --global user.name "Krellix-Bot"
          git config --global user.email "bot@krellix.com"
          git add .
          git commit -m "MAP_RECALIBRATED"
          git push
      - name: Close Issue
        run: gh issue close ${{ github.event.issue.number }} --comment "Target Neutralized."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
